Adding support for neovim `vim.ui.select`
lervag/wiki.vim pull request #281
Opened 2023-03-18 21:17 UTC by saccarosium

> related to: #274 

* Removing `WikiFzf{Pages,Tags,Toc}` in favor of `Wiki{Pages,Tags,Toc}`

This uses on Neovim `vim.ui.select` and on vim `junegunn/fzf`.

* Renaming `WikiPageToc` and `WikiPageLocToc` to `WikiGenerateToc` and `WikiGenerateLocToc`

This is for prefenting user confusion with `WikiToc` and also make more clear the outcome of the command.

## Demos

### with [FzfLua](https://github.com/ibhagwan/fzf-lua)

`WikiPages`
![pages](https://user-images.githubusercontent.com/96259932/226139905-b8662499-144b-4546-ab8f-64c065d824ae.gif)

`WikiTags`
![tags](https://user-images.githubusercontent.com/96259932/226139950-2cec9585-1798-45df-835b-1e9f22de6cea.gif)

`WikiToc`
![toc](https://user-images.githubusercontent.com/96259932/226139953-b1762ba0-4819-428d-a125-56db16e9426a.gif)

### with [Telescope](https://github.com/nvim-telescope/telescope.nvim)

`WikiPages`
![pages](https://user-images.githubusercontent.com/96259932/226140541-29ea432d-321b-42b1-8d1f-71394f2fd0fe.gif)

`WikiTags`
![tags](https://user-images.githubusercontent.com/96259932/226140498-c43bcd09-20c4-4b48-8326-6c47bd3680da.gif)

`WikiToc`
![toc](https://user-images.githubusercontent.com/96259932/226140525-d21c6a71-48d6-4a30-ac71-5211cd251dd7.gif)

2023-03-21 21:02 UTC, lervag commented
> Removing `WikiFzf{Pages,Tags,Toc}` in favor of `Wiki{Pages,Tags,Toc}`
> 
> This uses on Neovim `vim.ui.select` and on vim `junegunn/fzf`.

Thank you, I really appreciate your work here! I was already working on this myself, but it was not going very fast. I'm glad to have help here!

> Renaming `WikiPageToc` and `WikiPageLocToc` to `WikiGenerateToc` and `WikiGenerateLocToc`

Thanks, I agree on this suggestion, except that I want it to be `WikiTocGenerate...` and similar for the mappings.

----

I believe we are quite close already with your effort, but we need some more work:

* Now we are "breaking" things for those who are using neovim who _wants_ to use fzf. I believe we could solve this with a new option, e.g. `g:wiki_select_method`. The default value would be `fzf` for Vim and `nvim` for neovim, and it would allow neovim users to revert to the old fzf backend.

* We need updated docs for the `Wiki{Pages,Tags,Toc}` commands that distinguish the command intents from the "implementation" (neovim vs fzf).

* Is it possible to somehow add a previewer with `vim.ui.select`?

* Is it possible and relevant to add a formatter for `wiki.pages()`?

* Is it possible and relevant to add a formatter for `wiki.toc()`?

2023-03-21 21:03 UTC, lervag requested changes

2023-03-22 09:43 UTC, saccarosium commented on plugin/wiki.vim
> +  command! WikiTags   call luaeval("require('wiki').get_tags()")
In theory there is no differce, but I'm not sure... If it work I think calling lua directly is cleaner.

2023-03-22 10:44 UTC, saccarosium commented on lua/wiki/init.lua
> +local M = {}
The most used in the Neovim's community is [StyLua](https://github.com/JohnnyMorganz/StyLua). You put a `.stylua.toml` and go from there.

2023-03-22 10:47 UTC, saccarosium commented on lua/wiki/init.lua
> +local M = {}
Btw, `M = {}` is a Neovim's plugins convention. We can also use `wiki = {}`.

2023-03-22 11:58 UTC, saccarosium commented
> Is it possible to somehow add a previewer with vim.ui.select?

I don't think is possible natively, or in a way that it is general enogh for all kinds of fuzzy finders.

> We need updated docs for the Wiki{Pages,Tags,Toc} commands that distinguish the command intents from the "implementation" (neovim vs fzf).

My plan was to write it myself but I need help on where is appropriate to make (under what heading/subsection)

2023-03-23 18:24 UTC, lervag commented on autoload/wiki/buffer.vim
> +  command! -buffer WikiGenerateToc        call wiki#toc#create(1)
Sorry, but I was probably unclear on my last sentence. You changed `WikiPageToc` to `WikiTocGenerate` now, but you did not change the map definition later on line 115:

```vim
  nnoremap <silent><buffer> <plug>(wiki-page-toc)             :WikiPageToc<cr>
```

2023-03-23 18:25 UTC, lervag commented on lua/wiki/init.lua
> +local M = {}
Thanks for the information!

2023-03-23 18:31 UTC, lervag commented
There's a minor detail left (line 115 of `buffer.vim`), and the docs. I can do the docs.

Also, I appreciate that you've used conventional commits here!

2023-03-23 18:35 UTC, merged

2023-03-23 19:20 UTC, lervag commented
I've merged this now and also pushed an update to the docs. Let me know what you think.

2023-03-23 20:39 UTC, saccarosium commented
I think is a good idea listing this integration in the README. As you saw in some of the GIFs if uploaded the user can use basecly every neovim fuzzy finder, is very cool!

2023-03-23 21:01 UTC, lervag commented
I've tried to list these now.